// Code generated by github.com/x-izumin/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/golang/mock/mockgen"
	_ "github.com/google/wire/cmd/wire"
	_ "github.com/x-izumin/gex/cmd/gex"
	_ "github.com/rakyll/statik"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go build -v -o=./bin/mockgen github.com/golang/mock/mockgen
//go:generate go build -v -o=./bin/wire github.com/google/wire/cmd/wire
//go:generate go build -v -o=./bin/gex github.com/x-izumin/gex/cmd/gex
//go:generate go build -v -o=./bin/statik github.com/rakyll/statik
